name: Deploying rpm repo
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "10 0 * * *" # run at the start of every day after postinstall scripts repo update
  workflow_dispatch:

env:
  public_key: ${{ secrets.PUBLIC }}
  private_key: ${{ secrets.PRIVATE }}

jobs:
  deploy-repo:
    runs-on: ubuntu-22.04
    steps:
      - name: Checking out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Installing dependencies
        run: sudo apt-get install -y rpm createrepo-c

      - name: Packing rpm package
        run: rpmbuild -bb eupnea-utils.spec

      - name: Creating repo
        run: bash create-repo.sh

      - name: Deploying repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: Deploying rpm-repo
          branch: gh-pages
          create_branch: true
          # Only include needed files
          file_pattern: 'repodata/* *.rpm eupnea-utils.repo public_key.gpg eupnea-utils.sha256'
          push_options: '--force'

      - name: Updating sha256sums
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: Updating sha256sums
          # Only include needed files
          file_pattern: 'eupnea-utils.sha256'